### ISSUE TITLE
Completion in k8s files

### ISSUE THREAD

**Issue by Aaronzinhoo** [TxGVNN/emacs-k8s-mode#7]
Do you know of a way to get completion added? I would be willing to add some for this mode, but I do not know where I would find the keywords for kubernetes files. Also do you plan to do anything with Helm in the future?

**Comment by TxGVNN** [comment]
> Do you know of a way to get completion added? I would be willing to add some for this mode, but I do not know where I would find the keywords for kubernetes files.

I think you don't need to find and add some more. Just see what you need and just make it become a yasnippet template.

> Also do you plan to do anything with Helm in the future?

Helm template is jinja file, so if you want to support helm, you should write a new helm-k8s-mode (because helm-mode name had taken)  instead of using this mode

**Comment by Aaronzinhoo** [comment]
Although I do agree that creating a yassnippet is convenient, I am still early in my journey and what I need is still kinda hard to determine. I was thinking of writing a completion backend with docs so that people like me can see the purpose of what they are using. 

Completion in kubernetes for the key values would be really helpful but it's a little difficult considering the contextual dependency of nested keys. Like spec can be a key under templates & service at two different levels.

**Comment by TxGVNN** [comment]
If I understand correctly, seems you should learn about company-mode for the completion feature. You will have to write a new company-backend function

**Comment by TxGVNN** [comment]
You can learn from https://github.com/rafalcieslak/emacs-company-terraform and https://github.com/krzysztof-magosa/company-ansible
